Repository UNLV-CS472-672/2025-S-GROUP1-URP, pull requests merged in 2025-04, with the labels that each got.

#81 Seperated garage maps
  App.js
  package-lock.json
  package.json
  src/components/ParkingMap/ParkingMap.js
  src/components/ParkingMap/initParkingData.js
Labels: bug, javascript

#83 Added input validation and Edit Vehicle Button
  App.js
  package-lock.json
  package.json
  screens/AddVehicleScreen.js
  screens/EditVehicleScreen.js
  screens/MyAccountScreen.js
Labels: dependencies, javascript

#94 Adding Photos to Vehicles
  package.json
  screens/AddVehicleScreen.js
  screens/EditVehicleScreen.js
  screens/RemoveVehicleScreen.js
Labels: javascript

#99 Added Random Spot Button
  src/components/ParkingMap/ParkingMap.js
Labels: javascript

#110 Enhance Add/Remove Vehicle Screens with Image Uploads, Navigation Fixes & Test Coverage
  package.json
  screens/AddVehicleScreen.js
  screens/MyAccountScreen.js
  screens/RemoveVehicleScreen.js
  screens/__tests__/AddVehicleScreen.test.js
  screens/__tests__/RemoveVehicleScreen.test.js
Labels: documentation

#125 removed the header text and fixed formatting on multiple screens
  App.js
  screens/AddVehicleScreen.js
  screens/CottageGroveParkingScreen.js
  screens/EditVehicleScreen.js
  screens/GatewayParkingScreen.js
  screens/MyAccountScreen.js
  screens/ReservationStatusScreen.js
  screens/TropicanaParkingScreen.js
Labels: bug, javascript

#123 Populated first floor of Cottage Grove Parking Map
  screens/CottageGroveParkingScreen.js
Labels: javascript

#140 changed icons and UI for the maps
  App.js
  assets/icons/account.png
  assets/icons/logout.png
  assets/icons/parking.png
  assets/icons/report.png
  screens/CottageGroveParkingScreen.js
  screens/GatewayParkingScreen.js
  screens/TropicanaParkingScreen.js
Labels: enhancement, javascript

#139 Map UI fixes
  screens/CottageGroveParkingScreen.js
Labels: javascript

#144 Tutorial new
  App.js
  assets/tutorial/URPLogo.png
  assets/tutorial/tut1.PNG
  assets/tutorial/tut2.PNG
  assets/tutorial/tut3.PNG
  assets/tutorial/tut4.PNG
  package-lock.json
  package.json
  screens/AddVehicleScreen.js
  screens/MyAccountScreen.js
  screens/TutorialScreen.js
  screens/signUpScreen.js
Labels: documentation, enhancement

#143 Resolved Test Failures and Completed Coverage for Component Screens
  __mocks__/firebase/firestore.js
  screens/ParkingScreen.js
  screens/ReservationStatusScreen.js
  screens/__tests__/EditVehicleScreen.test.js
  screens/__tests__/LoginScreen.test.js
  screens/__tests__/ParkingScreen.test.js
  screens/__tests__/ReservationConfirmationScreen.test.js
  screens/__tests__/ReservationStatusScreen.test.js
  screens/__tests__/ResetPasswordScreen.test.js
  screens/__tests__/signUpScreen.test.js
  screens/signUpScreen.js
Labels: unit test, dependencies
