Repository UNLV-CS472-672/2025-S-GROUP1-URP, pull requests merged in 2025-03, with the labels that each got.

#2 Adding login screen for app
  App.js
  login.js
Labels: enhancement

#37 Reservation Status Screen Unit Tests
  babel.config.js
  package-lock.json
  package.json
  screens/ReservationStatusScreen.js
  screens/__tests__/ReservationStatusScreen.test.js
Labels: enhancement, unit test

#65 updated the reservation status screen unit tests
  package.json
  screens/__tests__/ReservationStatusScreen.test.js
Labels: unit test

#72 Feature/parking map
  src/components/ParkingMap/ParkingMap.js
Labels: enhancement

#74 Bugfix/my account -
  screens/AddVehicleScreen.js
  screens/MyAccountScreen.js
Labels: enhancement
